import type { Metadata } from "next";
import { PageHero } from "@/components/layout/page-hero";
import { SectionHeading } from "@/components/ui/section-heading";

export const metadata: Metadata = { title: "Student Life", description: "Clubs, passion projects, internships, and competitions that extend learning beyond class." };
const opportunities = [["Clubs", "Find your people, build leadership, and make ideas happen together."], ["Passion Projects", "Develop an interest into a body of work that says something meaningful about you."], ["Internships", "Explore professional interests and learn from practical, real-world experience."], ["Competitions", "Challenge yourself through academic, creative, and collaborative opportunities."]];
export default function StudentLifePage() {
  return <><PageHero eyebrow="Student Life" title="Build a story beyond the classroom." description="The most memorable learning happens when students explore what matters to them." breadcrumbs={[{ label: "Home", href: "/" }, { label: "Student Life" }]} />
    <section className="section-padding"><div className="container-ascend"><SectionHeading eyebrow="Beyond academics" title="Experiences with real purpose." description="At Ascend, extracurricular development is part of the university journey—not an afterthought." /><div className="mt-10 grid gap-5 md:grid-cols-2">{opportunities.map(([title, description], i) => <article key={title} className="rounded-[2rem] border border-border bg-card p-7"><p className="font-serif text-4xl text-accent-gold">0{i + 1}</p><h2 className="mt-7 font-serif text-3xl">{title}</h2><p className="mt-4 max-w-md leading-relaxed text-muted-foreground">{description}</p></article>)}</div></div></section><section className="section-padding bg-surface-muted/50"><div className="container-ascend max-w-3xl text-center"><p className="eyebrow">Your initiative</p><h2 className="font-serif text-4xl">We help students turn curiosity into momentum.</h2><p className="mt-5 leading-relaxed text-muted-foreground">With mentoring, structure, and room to lead, students create work they are proud to share.</p></div></section></>;
}
